#!/bin/sh
clear
#colour
R='\033[1;31m'
B='\033[0;34m'
C='\033[0;36m'
G='\033[1;32m'
W='\033[1;37m'
Y='\033[0;33m'
Y2='\033[1;33m'
clear

				 cd $dir
                 rm -rf $dir/.bashrc
                 wget https://raw.githubusercontent.com/BabyDragoN-MarMu/bashrc/master/my-banner
                 clear
                 cd
                 read -p " Put Your Name Logo : " logo
                 sed "s/marmu/$logo/" $dir/my-banner > $dir/.bashrc
                 figlet -f big "   $logo" | lolcat
                 echo " Done"
                 rm -rf $dir/my-banner
                 sleep 2
			fi
cd $dir
gem install lolcat
rm -rf $dir/.bashrc
wget https://raw.githubusercontent.com/BabyDragoN-MarMu/bashrc/master/my-banner
clear
cd
#read logo
read -p " Put Your Name Logo : " logo
sed "s/marmu/$logo/g" $dir/my-banner > $dir/.bashrc
figlet -f big "   $logo" | lolcat
echo " Done"
rm -rf $dir/my-banner
sleep 1
