#!/bin/sh
clear
#colour
R='\033[1;31m'
B='\033[0;34m'
C='\033[0;36m'
G='\033[1;32m'
W='\033[1;37m'
Y='\033[0;33m'
Y2='\033[1;33m'
clear
cd $dir
gem install lolcat
chmod 777 $dir/.bashrc
rm -rf $dir/.bashrc
wget https://raw.githubusercontent.com/BabyDragoN-MarMu/bashrc/master/Marmu-Banner
clear
cd
#read logo
read -p " Put Your Name Logo : " logo
sed "s/marmu/$logo/g" $dir/Marmu-Banner > $dir/.bashrc
figlet -f big "   $logo" | lolcat
echo " Done"
rm -rf $dir/Marmu-Banner
sleep 1
